version: '3.7'

services:
  bootstrap.node:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    tty: true
    command: ["bash"]
    ports:
      - "8293:9001"